--- 
- name: Get Device Facts
  hosts: rsiteA-t2b01-vmx-junos
  gather_facts: no
 

  vars:
    ansible_connection: network_cli
    ansible_network_os: junos
    ansible_user: cn02945
    ansible_password: ebn10388**

  tasks:
  - name: Configure Display Login Banner
    junos_banner: 
       banner: login
       text: |
        *******************************************************************
        * This is CHRIS's PRIVATE NETWORK, UNAUTHORIZED USERS KEEP OUT!!! *
        * THIS NETWORK IS BEING MANAGED BY ANSIBLE AUTOMATION NETWORK.    *
        *                                                                 *
        *  Authorized users are being loged...                            *
        *******************************************************************
        

        
       state: present
