--- 
- name: Get Device Facts
  hosts: rsiteA-t2b01-vmx-junos
  roles: 
    - Juniper.junos
  connection: local
  gather_facts: no
 
  vars_prompt: 
    - name: USERNAME
      private: no
      prompt: "User name"
    - name: DEVICE_PASSWORD
      private: true

  tasks:
  - name: Reboot All REs on the Device
    juniper_junos_system: 
       action: reboot
       user: "{{USERNAME}}"
       passwd: "{{DEVICE_PASSWORD}}"
