---
- name: Run commands on remote LAB devices
  hosts: rsiteA-dcc01-vEOS
  connection: local
  gather_facts: yes
 
  vars:
    username: cn02945
    password: ebn10388**
  
  tasks:
  - name: Gather facts (eos)
    eos_facts:
      gather_subset:
        - "!hardware"
    
    provider:
    authorize: yes
    auth_pass: ebn10388**
    
  - name: configure the login banner
    eos_banner:
     banner: login
     text: |
       this is my login banner
       that contains a multiline
       string
     state: present
