--- 
- 
  connection: local
  gather_facts: false
  hosts: eos_devices
  name: "EOS Show Commands"
  tasks: 
    - 
      eos_command: 
        commands: 
          - "show version | i Arista"
      name: "eos show commands"
      provider: "{{ cli }}"
      register: output
    - 
      debug: ~
      name: "show output"
      var: output
  vars: 
    cli: 
      authorize: true
      host: rsiteA-dcc01-vEOS
      transport: cli
...
