--- 
- 
  connection: local
  gather_facts: false
  hosts: rsiteA-t2b01-vmx-junos
  name: "Get Device Facts"
  roles: 
    - Juniper.junos
  tasks: 
    - 
      juniper_junos_system: 
        action: reboot
        passwd: 
          ? 
            DEVICE_PASSWORD: ~
          : ~
        user: 
          ? 
            USERNAME: ~
          : ~
      name: "Reboot all REs on the device"
      register: response
  vars_prompt: 
    - 
      name: USERNAME
      private: false
      prompt: "User name"
    - 
      name: DEVICE_PASSWORD
      private: true
