---

- name: Get Device Facts
  hosts: rsiteA-t2b01-vmx-junos
  connection: local
  gather_facts: yes
  
  tasks:
    - name: "Configure Display LOGIN Message"
      juniper.device.config:
        load: "set"
        lines:
          - set system login message "THIS IS A PRIVATE NETWORK, UNAUTHORIZED USERS KEEP OUT!!! YOU WILL BE PERSUCUTED TO FULL EXTENT OF THE LAW!!!"
      register: response

    - name: Print version
      debug:
        var: junos.version
...
