---
- name: Run commands on remote LAB devices
  hosts: rsiteA-dcc01-vEOS
  connection: network_cli
  gather_facts: yes
  
  vars:
    ansible_network_os: eos
    ansible_become: yes
    ansible_become_method: enable
    ansible_user: cn02945
    ansible_password: ebn10388**

  tasks:
  - name: configure the login banner
    eos_banner:
     banner: login
     text: |
       *******************************************************************
       * This is CHRIS's PRIVATE NETWORK, UNAUTHORIZED USERS KEEP OUT!!! *
       * THIS NETWORK IS BEING MANAGED BY ANSIBLE AUTOMATION NETWORK.    *
       *                                                                 *
       *  Authorized users are being loged...                            *
       *******************************************************************
     state: present
