---
- name: Run commands on remote LAB devices
  hosts: rsiteA-dcc01-vEOS
  connection: local
  gather_facts: yes
  username: cn02945
  password: ebn10388**

  tasks:
    - name: Configure the login banner
      eos_banner:
        banner: login
        text: |
           * ********************************************************** *
           * This is a PRIVATE NETWORK! UNAUTHORIZED USERS KEEP OUT!!!  *
           * THIS SWITCH IS MANAGED VIA ANSIBLE NETWORK AUTOMATION!!!!  *
           * You will be PUNISH on the FULL Extent of the LAW!!!        * 
           *                                                            *
           *  All Access to this device is loged.                       *
           * ********************************************************** *      
        state: present
  
