---
- name: Run commands on remote LAB devices
  hosts: rsiteA-dcc01-vEOS
  connection: local
  gather_facts: yes
  
  vars:
    username: cn02945
    passsowrd: ebn10388**

  tasks:
    - name: Configure the login banner
      eos_banner:
        text: |
           This is a PRIVATE NETWORK! UNAUTHORIZED USERS KEEP OUT!!!
           You will be PUNISH on the FULL Extent of the LAW!!!
      
        state: present
  
