---
- name: Run commands on remote LAB devices
  hosts: rsiteA-dcc01-vEOS
  connection: local
  gather_facts: yes

  tasks:
  - name:
    eos_command:
     username: cn02945
     password: ebn10388**
     transport: eapi
     use_ssl: true
 
  - name: configure the login banner
    eos_banner:
     banner: login
     text: |
       this is my login banner
       that contains a multiline
       string
     state: present
