---

- name: Get Device Facts
  hosts: rsiteA-t2b01-vmx-junos
  connection: local
  gather_facts: yes
  
  tasks:
    - name: "Configure Display LOGIN Message"
       junipernetworks.junos.junos_command:
            commands: show version
       register: response

    - name: Print version
      debug:
        var: junos.version
...
