---
- name: Run commands on remote LAB devices
  hosts: rsiteA-dcc01-vEOS
  connection: network_cli
  ansible_network_os: eos
  become: yes
  gather_facts: no

  tasks:
  - name: configure the login banner
    eos_banner:
     banner: login
     text: |
       this is my login banner
       that contains a multiline
       string
     state: present
